Repository Kohulan/DECIMER-Image-Segmentation, pull requests merged in 2023-09, with the labels that each got.

#77 Horizontal vertical line exclusion
  decimer_segmentation/complete_structure.py
  tests/test_mask_expansion.py
Labels: enhancement

#78 fix: handle failed mask center determination #63
  decimer_segmentation/complete_structure.py
Labels: bug

#80 fix: smaller threshold for definition of long vertical or horizontal lines
  decimer_segmentation/complete_structure.py
Labels: enhancement

#87 feat: GH Action for automated Pypi releases
  .github/workflows/pypi_release.yml
Labels: enhancement

#94 chore(master): release 1.2.3
  CHANGELOG.md
  setup.py
Labels: autorelease: pending
